musnix/musnix

default.nix
https://github.com/musnix/musnix/issues/14
=> Fix bug where kernel packages are not updated.

default.nix, modules/rtirq.nix, pkgs/rtirq/default.nix
Opening this to track progress...
I will squash and merge when it is ready.
=> rtirq support

pkgs/os-specific/linux/kernel/linux-4.1-rt.nix, pkgs/os-specific/linux/kernel/patches.nix
Tested-by: kmicu <kmicu@protonmail.ch>
=> kernel: 4.1.7-rt8 -> 4.1.10-rt10

pkgs/os-specific/linux/kernel/linux-4.6-rt.nix, pkgs/os-specific/linux/kernel/patches.nix
=> kernel: 4.6.5-rt9 -> 4.6.7-rt11

modules/kernel.nix, pkgs/os-specific/linux/kernel/linux-4.8-rt.nix, pkgs/os-specific/linux/kernel/patches.nix
with modinst_arg_list_too_long patch
that is missing from https://github.com/musnix/musnix/pull/36
=> kernel: add 4.8-rt1

pkgs/os-specific/linux/kernel/linux-4.8-rt.nix, pkgs/os-specific/linux/kernel/patches.nix
=> kernel: add 4.8.15-rt10

README.md
That will make it much easier to install and update musnix.
/cc @erlandsona
=> README: prefer installation via nix-channel

pkgs/os-specific/linux/kernel/linux-3.18-rt.nix, pkgs/os-specific/linux/kernel/linux-4.1-rt.nix, pkgs/os-specific/linux/kernel/linux-4.11-rt.nix, pkgs/os-specific/linux/kernel/linux-4.13-rt.nix, pkgs/os-specific/linux/kernel/linux-4.14-rt.nix, pkgs/os-specific/linux/kernel/linux-4.4-rt.nix, pkgs/os-specific/linux/kernel/linux-4.9-rt.nix
I am still building the kernel at the moment, so this is untested.
=> fix issue #64

pkgs/os-specific/linux/kernel/linux-4.14-rt.nix, pkgs/os-specific/linux/kernel/patches.nix
4.14.15-rt12 builds and runs, but when I reboot, it hangs.
4.14.15-rt13 seems fine.
=> kernel: 4.14.12-rt10 -> 4.14.15-rt13

README.md, modules/kernel.nix, pkgs/os-specific/linux/kernel/patches.nix
=> kernel: add 4.18.5-rt3

README.md, modules/kernel.nix, pkgs/os-specific/linux/kernel/patches.nix
=> Revert "kernel: add 4.18.5-rt3"

pkgs/os-specific/linux/kernel/linux-4.19-rt.nix, pkgs/os-specific/linux/kernel/patches.nix
This verison works. Been running it for couple days and see no issues.
=> 4.19.15-rt12 -> 4.19.25-rt16

modules/kernel.nix
I don't know why but this fixes #108 for me
=> fixes #108

tests/default.nix
To run this test:
```
cd tests
nix-build
```
Ref:
https://nixos.org/nixos/manual/#sec-writing-nixos-tests
=> tests: update to use python testing harness

overlay.nix
This fixes the issue of not being able to use musnix on latest stable nixos-20.03 due to the lacking `lib.kernel`.
These functions can be removed as soon as 20.09 becomes stable. 
https://github.com/musnix/musnix/issues/123
=> Add missing functions to compile on nixos-20.03

overlay.nix, pkgs/os-specific/linux/kernel/linux-5.9-rt.nix, pkgs/os-specific/linux/kernel/metadata.nix, pkgs/os-specific/linux/kernel/patches.nix, pkgs/os-specific/linux/kernel/update.sh
Add 5.9 realtime kernel and update all the patches
=> Add 5.9 kernel

pkgs/os-specific/linux/rtirq/default.nix
Also adds a fallback scheme to prevent my system from breaking every few months
=> rtirq 20210113 -> 20210309

modules/base.nix
=> support plugin paths installed by home-manager

README.md, modules/kernel.nix, overlay.nix, pkgs/os-specific/linux/kernel/linux-6.0-rt.nix, pkgs/os-specific/linux/kernel/metadata.nix, pkgs/os-specific/linux/kernel/patches.nix
Partially addressing #151.
Tested locally.
=> kernel: add 6.0.5-rt14, make latest

README.md, modules/kernel.nix, overlay.nix, pkgs/os-specific/linux/kernel/linux-5.15-rt.nix, pkgs/os-specific/linux/kernel/metadata.nix, pkgs/os-specific/linux/kernel/patches.nix, release.nix
Partially addressing #151.
Tested locally.
=> kernel: add 5.15.76-rt53, make default

modules/base.nix
Also sort environment variables alphanumerically
=> Add CLAP plugin path

README.md, modules/kernel.nix, pkgs/os-specific/linux/kernel/metadata.nix
Ran the kernel update script:
6.1.83-rt28 -> 6.1.90-rt30
6.6.23-rt28 -> 6.6.30-rt30
6.8.0-rt8 -> 6.8.2-rt11
=> updated kernel versions

README.md
whoops, forgot to update the docs :slightly_smiling_face:
=> update available kernel versions in readme
