default.nix

The old version, 3.14.31-rt28, is incompatible with a patch recently added to the nixpkgs release-14.12 branch (https://github.com/NixOS/nixpkgs/commit/f01dd23aafaa816f00a4acb42bed5a724e5dd8ba).

update realtime kernel to 3.14.36-rt34

---

README.md
modules/kernel.nix
pkgs/os-specific/linux/kernel/linux-3.14-rt.nix
pkgs/os-specific/linux/kernel/linux-3.18-rt.nix
pkgs/os-specific/linux/kernel/linux-4.0-rt.nix
pkgs/os-specific/linux/kernel/patches.nix

Opening this to track progress...
Important changes:
* Users will be able to choose from several available real-time kernels.  This is done by setting `musnix.kernel.packages` to one of the following packages:  
* `pkgs.linuxPackages_3_14_rt`
* `pkgs.linuxPackages_3_18_rt` (default)
* `pkgs.linuxPackages_4_0_rt`
* For real-time kernels, rather than applying the `CONFIG_PREEMPT_RT` patches using overrides, the patches are now directly applied to three new kernel derivations.   The patch expressions have also been moved to a separate file.  This approach is similar to what is used in [nixpkgs](https://github.com/NixOS/nixpkgs/tree/master/pkgs/os-specific/linux/kernel), and facilitates moving some of this work there when the time comes.  
* At that point, we'd probably add something like: …

Refactor kernel.nix, add 3.18.17-rt14 and 4.0.5-rt4 kernels

---

pkgs/os-specific/linux/kernel/linux-3.14-rt.nix
pkgs/os-specific/linux/kernel/linux-3.18-rt.nix
pkgs/os-specific/linux/kernel/linux-4.0-rt.nix

Fixes the following build error:
```
make[1]: Leaving directory '/tmp/nix-build-linux-3.18.17.drv-0/build'
unlink: cannot unlink '/nix/store/bjmsfxxi82i0gxq3i8hzi4nj6nsz61hk-linux-3.18.17/lib/modules/3.18.17/build': No such file or directory
builder for ‘/nix/store/6w9w916z5gl835hsz2m3p4dq9njlagd3-linux-3.18.17.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/d534vj66389wv3zsy6pqyj9xxpcb616p-nixos-15.07pre66213.9d5508d.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/d534vj66389wv3zsy6pqyj9xxpcb616p-nixos-15.07pre66213.9d5508d.drv’ failed
```

kernel: append rt patch revision to version

---

README.md
default.nix
modules/other.nix

Do you agree this belongs in musnix?
It makes sure your machine doesn't lock up even if there are RT processes taking up all the resources.
(after https://github.com/NixOS/nixpkgs/pull/7987 gets merged, that is)

add das_watchdog: a realtime watchdog

---

pkgs/os-specific/linux/kernel/patches.nix

Use a stable URL for the patches.
e.g. https://www.kernel.org/pub/linux/kernel/projects/rt/4.6/
contains only the latest patch
while https://www.kernel.org/pub/linux/kernel/projects/rt/4.6/older/
contains all patches including the latest

kernel: fix rt patch url

---

README.md
modules/kernel.nix
pkgs/os-specific/linux/kernel/linux-4.9-rt.nix
pkgs/os-specific/linux/kernel/patches.nix

17.03 is out!
17.03 introduces changes in the kernel configuration machinery, so **I'm proposing that we maintain a [`pre-17.03`](https://github.com/musnix/musnix/tree/pre-17.03) branch for users who wish to stay on 16.09 or earlier**.  I'd probably continue to focus my maintenance efforts on `master` but would gladly accept PRs against the `pre-17.03` branch from people who wanted to keep things current for earlier versions.
Does this sound good?
cc @magnetophon @erlandsona @tg-x @pngwjpgh @peterhoeg 
(or anyone else who might have a horse in this race)
Ref: #39

update for 17.03

---

pkgs/os-specific/linux/kernel/linux-3.18-rt.nix
pkgs/os-specific/linux/kernel/linux-4.1-rt.nix
pkgs/os-specific/linux/kernel/linux-4.4-rt.nix
pkgs/os-specific/linux/kernel/linux-4.6-rt.nix
pkgs/os-specific/linux/kernel/linux-4.8-rt.nix
pkgs/os-specific/linux/kernel/linux-4.9-rt.nix

without this, the kernels [do not build on 17.09](https://github.com/musnix/musnix/issues/43).

add hostPlatform to each kernel

---

modules/kernel.nix

In `common-config.nix`, the `RT_GROUP_SCHED` flag is set explicitly to `n` in a non-optional manner.
See here:
https://github.com/NixOS/nixpkgs/blob/7cdd12e4e977a39c570442a0728d217ff4ca177a/pkgs/os-specific/linux/kernel/common-config.nix#L466
The rt patch set includes a patch that makes this flag depend on `PREEMPT_RT_FULL` not being set to `y`.  In other words, when we set `PREEMPT_RT_FULL` to `y`, we effectively remove this flag and our ability to set it.
However, this causes an rt kernel build to fail for us because the default kernel configuration has explicitly set `RT_GROUP_SCHED` to `n`, and in our case, because of the aforementioned dependency and the fact that we are setting `PREEMPT_RT_FULL` to `y`, this flag no longer "exists" nor is it configurable.
By overriding the …

override RT_GROUP_SCHED explicitly in rt config

---

README.md

Fixes a typo, `musix.enable -> musnix.enable`.

README: fixup

---

pkgs/os-specific/linux/rtirq/default.nix

Hello
Old version of rtirq seems no longer available ( http://www.rncbc.org/jack/rtirq-20150216.tar.gz ), so the build fails on machines which do not have the source in nix store beforehand. I simply update the version to resolve the issue.

rtirq: 20150216 -> 20180209

---

modules/kernel.nix

This drops HPET_TIMER per #41, TREE_RCU_TRACE because it is not relevant to rt
and was not enabled before it was removed, RT_GROUP_SCHED because it was a
workaround for https://github.com/NixOS/nixpkgs/commit/96fbdf85.
Fixes #41, fixes #100

modules/kernel: switch to structuredExtraConfig

---

modules/rtirq.nix

The current usage triggers the warning from
https://github.com/NixOS/nixpkgs/pull/63103/commits/03309899:
trace: warning: In file /home/uj/nix/musnix/modules/rtirq.nix
a list is being assigned to the option config.environment.etc.
This will soon be an error as type loaOf is deprecated.
See https://github.com/NixOS/nixpkgs/pull/63103 for more information.
Do
environment.etc =
{ rtirq.conf = {...}; }
instead of
environment.etc =
[ { target = "rtirq.conf"; ...} ]

modules/rtirq: update usage of environment.etc

---

modules/kernel.nix

Linux 5.4 has integrated a part of the realtime patch.
PREEMPT_RT_FULL was renamed to PREEMPT_RT.

Enable PREEMPT_RT in linux_rt 5.4 and newer

---

default.nix
modules/kernel.nix
modules/rtirq.nix
overlay.nix
pkgs/os-specific/linux/kernel/linux-3.18-rt.nix
pkgs/os-specific/linux/kernel/linux-4.1-rt.nix
pkgs/os-specific/linux/kernel/linux-4.11-rt.nix
pkgs/os-specific/linux/kernel/linux-4.13-rt.nix
pkgs/os-specific/linux/kernel/linux-4.14-rt.nix
pkgs/os-specific/linux/kernel/linux-4.16-rt.nix
pkgs/os-specific/linux/kernel/linux-4.18-rt.nix
pkgs/os-specific/linux/kernel/linux-4.19-rt.nix
pkgs/os-specific/linux/kernel/linux-4.4-rt.nix
pkgs/os-specific/linux/kernel/linux-4.9-rt.nix
pkgs/os-specific/linux/kernel/linux-5.0-rt.nix
pkgs/os-specific/linux/kernel/linux-5.4-rt.nix
pkgs/os-specific/linux/kernel/linux-5.6-rt.nix
release.nix

i took some inspiration from the old overlay-branch.
- this provides an `overlay.nix` that can be used like a regular overlay.
- using `latencytop` or `optimize` can either be enabled in the module or by overriding the packages `enableLatencytop` and `enableOptimization`.
- `rtirq` got moved into the overlay aswell.

convert to overlay

---

pkgs/os-specific/linux/kernel/linux-3.18-rt.nix
pkgs/os-specific/linux/kernel/linux-4.1-rt.nix
pkgs/os-specific/linux/kernel/linux-4.11-rt.nix
pkgs/os-specific/linux/kernel/linux-4.13-rt.nix
pkgs/os-specific/linux/kernel/linux-4.14-rt.nix
pkgs/os-specific/linux/kernel/linux-4.16-rt.nix
pkgs/os-specific/linux/kernel/linux-4.18-rt.nix
pkgs/os-specific/linux/kernel/linux-4.19-rt.nix
pkgs/os-specific/linux/kernel/linux-4.4-rt.nix
pkgs/os-specific/linux/kernel/linux-4.9-rt.nix
pkgs/os-specific/linux/kernel/linux-5.0-rt.nix
pkgs/os-specific/linux/kernel/linux-5.4-rt.nix
pkgs/os-specific/linux/kernel/linux-5.6-rt.nix
pkgs/os-specific/linux/kernel/metadata.nix
pkgs/os-specific/linux/kernel/patches.nix
pkgs/os-specific/linux/kernel/update.sh

depends on #116 
**motivation:**
i noticed that some kernel-packages and patches weren't up-to-date.
**description:**
i adopted the `metadata.nix` approach.
- `metadata.nix` contains versions and hashes for all packages.
- all packages use the information from `metadata.nix`
- `metadata.nix` can be automatically updated using `update.sh`

Metadata update script

---

modules/base.nix

This sets the `VST3_PATH` environment variable.

Add VST3 path

---

pkgs/os-specific/linux/rtirq/default.nix

Needed because stdenv.lib is deprecated and no longer supported by nixOS

Update musnix/rtirq for usage on nixos-unstable (20.11)

---

README.md
flake.lock
flake.nix

NixOS flake support for musnix, will function the same way as regular nix-channel or clone.

Flake: Initial Musnix Flake support

---

pkgs/os-specific/linux/rtirq/default.nix

`rtirq` no longer builds on nixpkgs master because it uses a now-obsolete alias of `util-linux` (see https://github.com/NixOS/nixpkgs/pull/104776, https://github.com/NixOS/nixpkgs/commit/d06207386df9a53fe01f8a30130dfc9a839fc8fc, https://github.com/NixOS/nixpkgs/commit/ba3319568df2c6675dbe36478fb3edf16e114ac3). This tiny PR removes the use of the alias.

utillinux → util-linux

---

README.md

While trying out the module installation I tried to test `musnix.enable = true` was properly working by trying to read the value `2048` from `/proc/sys/dev/hpet/max_user_freq`. As the value was not updated, I thought I was doing something wrong setting up my configuration files. Then I found out [this commit](https://github.com/musnix/musnix/commit/e6850703264e2558f19343c01d901808c7be17f6) where those values are taken away from the configuration.
Even if it's not a complete proposal of documentation update, I hope taking this references out will prevent others from getting confused like I was :)

Remove references to max_user_freq

---

README.md
modules/kernel.nix
overlay.nix
tests/default.nix

As discussed in #149, it looks like the `kernel.latencytop` and `kernel.optimize` settings didn't survive the transition to the overlay.  IIRC, the features of the latter have been subsumed into the mainline kernel defaults.
It's not yet clear to me how to make them work as they once did, but I think it's best if we remove them for now, as they are basically broken.

remove kernel.{latencytop,optimize} features

---

overlay.nix

Enableing realtime changes 2 symbols from export to gpl only which prevents zfs from loading. This patch is default on nixos rt kernels.
The 6.0 kernel compiles and starts but gets a oops late in the boot process when devices ar created, could be nvidia as well. But at leas, compiles now

Add export patch export-rt-sched-migrate to all kernel to enable zfs

---

modules/base.nix

This group is already [pre-configured](https://github.com/NixOS/nixpkgs/blob/33c9fd85e52f925e05f4a6bd69811f97e5ccdc15/nixos/modules/config/users-groups.nix#L572) in NixOS installations

Don't create audio group

---

modules/base.nix

From 18.09 onwards, the package for ffado is `ffado` instead of `ffadoFull`.

Fix ffado.enable to point to proper ffado package

---

modules/base.nix

It seems that the current master branch still had the "ffadoFull" notation.
A small change finally fixed the error on `nixos-rebuild switch`.
pkgURL: https://search.nixos.org/packages?channel=23.05&show=ffado&from=0&size=50&sort=relevance&type=packages&query=ffado

Replaced from ffadoFull to ffado on the line62.

---

modules/base.nix

It seems like the `threadirqs` kernel parameter[1] is missing an `s`
[1]: https://docs.kernel.org/admin-guide/kernel-parameters.html

Fix missing s in threadirqs kernel parameter

---

modules/base.nix

Currently to override any plugin envvars set by musnix, you must use lib.mkForce.  This makes it possible to disuse lib.mkForce, and is backwards compatible.
If someone can think of a way to test this, I'd be happy to add a test too.

Allow overrides of environment variables without mkForce

---

README.md
modules/base.nix

Enables DAWs like Ardour and Reaper to set CPU DMA latency, found via "rtcqs".

add udev rule to allow users in the audio group to change cpu dma latency

---

.github/workflows/eval.yml
flake.lock
flake.nix
tests/default.nix
tests/lib.nix

As mentioned in #173 this is a way to allow tests to be run that do not depend on the version of nixpkgs being used locally.
It changes the test regime such that it suggests running `nix flake check -L` instead of `nix-build tests/default.nix`.  This means that the version of nixpkgs used during testing will be the one in `flake.lock`, and the nixpkgs version of the host becomes irrelevant.  It will require that the test-running-system has a Nix configuration that enables flakes.
This PR also updates the `flake.lock` file because the old lockfile pointed at a version of nixpkgs that could not build the newer musnix realtime kernel successfully.
EDIT: note that the changes in this PR also causes every other PR and push to run the musnix tests; this may or may not be desirable.

Use flake check for tests

---

.github/workflows/eval.yml
README.md
flake.lock
flake.nix
modules/base.nix
overlay.nix
pkgs/rtcqs.nix
tests/default.nix
tests/lib.nix
tests/musnix-test.py

I made this its own option, but I'd be ok with it if folks wanted to make it part of ``musnix.enable``.
One thing this helps with is detecting problems with config in the test.  It currently exposes a missing udev rule, which I hope to supply a fix for in an additional PR.

Add musnix.rtcsq.enable option and related test

---

flake.nix

I wanted to run `rtcqs` without having to install it. This allows nix (with flakes enabled) to get `rtcqs` via `nix run github:musnix/musnix#rtcqs`.

Add rtcqs to flake packages output

---

pkgs/os-specific/linux/rtirq/default.nix

Tested with ``nix-build -E 'with import <nixpkgs> {}; callPackage ./pkgs/os-specific/linux/rtirq {}'``

rtirq: cleanup, don't set phases, quote url, set pname

---

modules/kernel.nix
overlay.nix
pkgs/os-specific/linux/kernel/linux-6.9-rt.nix
pkgs/os-specific/linux/kernel/metadata.nix
pkgs/os-specific/linux/kernel/patches.nix
pkgs/os-specific/linux/kernel/update.sh

This adds 6.9.0 to the flake.
I'm unable to test this as I'm using ZFS on my system and 6.9.0 doesn't have zfs support yet in nixpkgs.
I can setup a test VM, which I will probably do regardless because I'd like to see it work. :-D

Add 6.9 kernel

---

modules/base.nix

In graphical sessions, that are started from a login manager, `environment.variables` aren't loaded, but `environment.sessionVariables` are

base.nix: use sessionVariables

---

modules/kernel.nix
overlay.nix
pkgs/os-specific/linux/kernel/linux-6.11-rt.nix
pkgs/os-specific/linux/kernel/metadata.nix
pkgs/os-specific/linux/kernel/patches.nix

Currently compiling on my 7th gen Intel :hourglass_flowing_sand:
* Added definition for 6.11 kernel
* Added definition for 6.11-rt7 patches
* Turned `metadata.nix` into a "table" (sorry, couldn't help myself :grin:)
What I don't understand is why there are still separate RT patches provided at (https://cdn.kernel.org/pub/linux/kernel/projects/rt/6.11/), if RT support has been upstreamed? Perhaps someone here could enlighten me (xref https://github.com/musnix/musnix/issues/206)

add support for 6.11-rt7

---

modules/base.nix

Yabridge picks the first variable for clap plugins to store files. This changes the first variable to the user directory so that Yabridge can work as intended. Without this fix clap fails to sync/update installed plugins(borked).

Update environment variables base.nix
